library(shiny)
library(httpuv)

shinyUI(pageWithSidebar(
  headerPanel("Annual Average Temperature Predictions from Ensemble General Circulation Models"),
  sidebarPanel(
    em("Instructions for map 1 and map 2:"),
    br(),
    em("1. select one climate scenario (e.g., `pre-2000`)"),
    br(),
    em("2. select a two-decade range (e.g., `1920-1939`)"),
    br(),
    em("3. view difference in maps 1 and 2 (bottom plot)"),
    br(),
    br(),
    em("This could take up to 6 minutes to load figures, so please be patient (go grab a coffee!)."),
    br(),
    br(),
    #p(a("Further documentation available here",href="/Users/nicolegoebel/Desktop/tempPredict_oneplot/www/documentation.html", target="_blank")),
    br(),
    checkboxGroupInput("scen1", label = h3("Select a scenario for map 1"), 
                       choices = list("pre-2000" = "past", "post-2000: 850 ppm by 2100 (a2)"="a2","post-2000: 550 ppm by 2100 (b1)"="b1"), selected = "past"),
    conditionalPanel(condition = "input.scen1 == 'past'",
                     selectInput("yearspred1a", h2("Select hindcasted years for map 1"),choices = list("1920-1939", "1940-1959", "1960-1979", "1980-1999"))),
    conditionalPanel(condition = "input.scen1 == 'a2'",
                     selectInput("yearspred1b", h2("Select predicted years for map 1"),choices = list("2020-2039", "2040-2059","2060-2079", "2080-2099"))),
    conditionalPanel(condition = "input.scen1 == 'b1'", 
                     selectInput("yearspred1c", h2("Select predicted years for map 1"),choices = list("2020-2039", "2040-2059", "2060-2079", "2080-2099"))),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    checkboxGroupInput("scen2", label = h3("Select a scenario for map 2"),
                       choices = list("pre-2000" = "past", "post-2000: 850 ppm by 2100 (a2)"="a2","post-2000: 550 ppm by 2100 (b1)"="b1"), selected = "past"),
    conditionalPanel(condition = "input.scen2 == 'past'",
                     selectInput("yearspred2a", h2("Select hindcasted years for map 2"),choices = list("1920-1939", "1940-1959", "1960-1979", "1980-1999"))),
    conditionalPanel(condition = "input.scen2 == 'a2'",
                     selectInput("yearspred2b", h2("Select predicted years for map 2"),choices = list("2020-2039", "2040-2059","2060-2079", "2080-2099"))),
    conditionalPanel(condition = "input.scen2 == 'b1'",
                     selectInput("yearspred2c", h2("Select predicted years for map 2"),choices = list("2020-2039", "2040-2059", "2060-2079", "2080-2099"))),
    br(),
    br(),  
    br(),  
    br(),  
    br(),  
    br(),  
    br(),  
    br(),  
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    h3("Map 3: difference in selections for map 1 and map 2"),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br(),
    br()
  ),
  mainPanel(
    h3(textOutput("add1")),
    imageOutput("plot1"),
    h3(textOutput("add2")),
    imageOutput("plot2"),    
    h3(textOutput("add3")),
    imageOutput("plotdiff"),
    HTML("More information about the general circulation model ensembles can be found at the <a href='www.data.worldbank.org/'> World Bank website</a>.")
  )  
)
)